//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_New
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public string TargetType { get; set; }
        public Nullable<int> TargetID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
